name: capppppp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio:
  provider:
  flutter_svg:
  http:
  wave:
  url_launcher: ^6.1.5
  agora_rtc_engine: ^4.0.7
  permission_handler: ^10.0.0
  flutter_custom_clippers:
  image_picker:
  image:
  google_fonts:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - D:\capppppp\WhatsApp Image 2024-10-14 at 7.34.32 PM.jpeg

linter:
  include: package:flutter_lints/flutter.yaml
  rules:
  # avoid_print: false  # Uncomment to disable the `avoid_print` rule
  # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
